// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdpO6mZlL76IO36AQOGX6-bLKsRDWfTBo',
    appId: '1:709112192978:android:576d081d2a468736e2720b',
    messagingSenderId: '709112192978',
    projectId: 'n3final',
    storageBucket: 'n3final.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsgtkUT9k4XuYRQYswW2NYDad5VcD_2g',
    appId: '1:709112192978:web:b4aed645ddffea4fe2720b',
    messagingSenderId: '709112192978',
    projectId: 'n3final',
    authDomain: 'n3final.firebaseapp.com',
    storageBucket: 'n3final.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5h3_cjFrElGleVGH8e6WmBkbPfuauEiI',
    appId: '1:709112192978:ios:1c258ae4171a4abee2720b',
    messagingSenderId: '709112192978',
    projectId: 'n3final',
    storageBucket: 'n3final.firebasestorage.app',
    iosBundleId: 'com.example.n3tassi',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5h3_cjFrElGleVGH8e6WmBkbPfuauEiI',
    appId: '1:709112192978:ios:1c258ae4171a4abee2720b',
    messagingSenderId: '709112192978',
    projectId: 'n3final',
    storageBucket: 'n3final.firebasestorage.app',
    iosBundleId: 'com.example.n3tassi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVsgtkUT9k4XuYRQYswW2NYDad5VcD_2g',
    appId: '1:709112192978:web:ffa022f0307a47bde2720b',
    messagingSenderId: '709112192978',
    projectId: 'n3final',
    authDomain: 'n3final.firebaseapp.com',
    storageBucket: 'n3final.firebasestorage.app',
  );

}